{% set version = "0.7" %}

package:
  name: pytest-mpl
  version: {{ version }}

source:
  fn: pytest-mpl-{{version}}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-mpl/pytest-mpl-{{version}}.tar.gz
  md5: 9c9bc0f4b48c14497600fde10db07336

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - matplotlib
    - nose

test:
  commands:
    - "py.test --traceconfig | grep pytest-mpl-{{version}}"

about:
  home: https://github.com/astrofrog/pytest-mpl
  license: BSD
  summary: 'pytest plugin to help with testing figures output from Matplotlib'

extra:
  recipe-maintainers:
    - dopplershift
    - astrofrog
