{% set name = "pytest-mpl" %}
{% set version = "0.8" %}
{% set sha256 = "d8c67a781cfd011fd9f20cb5a957f62701afcc5b44685c98369e1c22df960ccd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{name}}-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - matplotlib
    - nose

test:
  commands:
    - "py.test --traceconfig | grep pytest-mpl-{{version}}"

about:
  home: https://github.com/astrofrog/pytest-mpl
  license: BSD 2-Clause
  license_family: BSD
  summary: 'pytest plugin to help with testing figures output from Matplotlib'
  dev_url: https://github.com/astrofrog/pytest-mpl

extra:
  recipe-maintainers:
    - dopplershift
    - astrofrog
