travis:
  secure:
    BINSTAR_TOKEN: zqDeNmPHXDLt6hLrDVADHOkjA+x5LxTN2CMm9fvWNa1IjmFEvwvTYknD1hPqNtcR0LFgq7LsdlFd1cEX7EhIsqIbe1aQ9zMEqU3F/AjG3xprtDZLKc1anE9L1pegR1lqJEgma29RuY7GG9jAfubJjRSG4CUcs1WY/WBtPrbkuGSlUWmGcSgyLF2cO8i6lb/m9lWNjutgDhlOiE5b6UGzqBzM2jKTYoFPgovNQvPDcKb5XgjReJIdQ0WYSSxu+ykK3QjtKlwe7SnRJR4XpFhvVEjfp6Y6tagOwgcfW2U5rWY6JKLmgGJg5rl80Lpm2P1QRoJqQ2uwI5HKJeP9w67ETDRGQRGme2gCNOXRHk/xRD+3/oFKEmR2gpf9hGPWHviVODb6o4ddO0UGltUp+3Usc8ItfYU2ti+ifl+G2zWlBiDZGWHgaqxwEm6zQd6e7dYLqBpeWlo646sxXuhFblLa8buaQG7OD3q4bjZD6moafqt+W7W/3e5fPQzhZgWF+nlBHzNPG7XUUFICNj0bYwxYcYujthFUnBhbAtuoxg+3SVfMeQdSh82JozTWF52TnvNQDAv1vPA/SvauXblyDlZMH0H5Y/i9nhuWYPaV7FikOI7Qp19bd66EhOVbqxafKPN84GLMsECUAbmYAEVd+DVuBPtsUPRAbF6CAI7Lvxoodlk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
