travis:
  secure:
    BINSTAR_TOKEN: J6uMBw6DFoYiISU7mrB2EEuD9/4vuq21VBH7bymMjTpuaZvpi8L3ZbIMd3ElEoTFiE1yRVgxlqtZRddcVV47mI2qP0wTo03YDnBo1hXo3slPqBD6u5Or/NtlEimB+6YDza/kD0FshUXmBjw0I4bC5MMmvAMjGWuO0yriXd6FpcDP6jNU5P3TRhjQQ5Yoh9CxlxNJEWFwG5L2QKNaQGu6n7HCQP9txnMyPbHRyR5r2R9OH9g/Is6vmGFJCsjv8xZI/Ly1YiTGrMQ1StvSmX94mb1ivpfoz/CthPaxqwR6hjlZ1DmsA4uYvA6DeOrH5QS2KCDZ86I2hr9fTsgxrnVZsBXjhWw8Dy6VDodvDKhMOQDFP+FjCg7M3GUm9Z9w9Y6UCezQuiBiR+9Bq16Do7bZWfI1txDoS/Z3deaaijFxgn9tzVpbIpLd7bMmv1uwiWi5vPlnKcyhRxek97UisHR2olzZleXXqro/1t3KI0eK6CkDFMmGxpBrvLGnr8cLzgk+EZpuMY+NXQHTRJApg8qyXEQhqv0dW4YjPSzUO47i3xEOErkOUbphIXxqfGHCrG92nVImpnbZ5MN6uRqR6foe58KlK3x71oqogYioG5QXYz9cu7VpqWwaWN2LuDjywrkOBqQeIwo1RMZbfjT0yWK6JQQCgTi2n6STxdvPVSoG+Og=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
